apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdocdbcluster.aws.mojaloop.io
spec:
  defaultCompositeDeletePolicy: Foreground
  group: aws.mojaloop.io
  names:
    kind: XDocDbCluster
    plural: xdocdbcluster
  claimNames:
    kind: DocDbCluster
    plural: docdbcluster
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              managementPolicies:
                default:
                  - "*"
                description: |-
                  A ManagementAction represents an action that the Crossplane controllers
                  can take on an external resource.
                items:
                  description: |-
                    A ManagementAction represents an action that the Crossplane controllers
                    can take on an external resource.
                  enum:
                    - Observe
                    - Create
                    - Update
                    - Delete
                    - LateInitialize
                    - "*"
                  type: string
                type: array
              providerConfigsRef:
                type: object
                properties:
                  awsProviderConfigName:
                    type: string
                    description: AWS Provider Config Name
                  ccK8sProviderName:
                    type: string
                    description: |-
                      The name of the provider config to use for the local k8s provider.
                  httpProviderConfigName:
                    type: string
                    description: |-
                      The name of the provider config to use for the HTTP provider.
              parameters:
                type: object
                properties:
                  externalServiceName:
                    type: string
                    description: Name for the external service object created
                  appNamespace:
                    type: string
                    description: Namespace for the consumer application
                  caBundleUrl:
                    type: string
                    description: URL to the CA bundle of AWS
                  consumerAppsConfigMap:
                    type: object
                    properties:
                      name:
                        type: string
                        description: Name of the configmap
                      key:
                        type: string
                        description: Key in the configmap
                      namespaces:
                        type: array
                        items:
                          type: string
                        description: List of namespaces where the configmap is available
                  consumerAppsExternalServices:
                    type: array
                    items:
                      type: string
                    description: List of externalservice names for the consumer applications
                  databaseName:
                    type: string
                    description: Name for the created DB
                  allowMajorVersionUpgrade:
                    description: Indicates that major version upgrades are allowed
                    type: boolean
                    default: false
                  applyImmediately:
                    description: Indicates that changes should be applied immediately
                    type: boolean
                  backupRetentionPeriod:
                    description: The number of days to retain backups for
                    type: integer
                  dbClusterInstanceClass:
                    description: "Db instance class"
                    type: string
                  copyTagsToSnapshot:
                    description: Indicates that tags should be copied to snapshots
                    type: boolean
                    default: true
                  deletionProtection:
                    description: Indicates that deletion protection is enabled
                    type: boolean
                  engine:
                    description: The DB engine i.e mysql/postgres
                    type: string
                  engineVersion:
                    description: The DB version depends on the DB type and versions available in the selected provider.
                    type: string
                  family:
                    description: The family of the parameter group
                    type: string
                  finalSnapshotIdentifier:
                    description: The final snapshot identifier
                    type: string
                  enablePerformanceInsights:
                    description: Indicates that performance insights are enabled
                    type: boolean
                    default: false
                  instanceCount:
                    description: The number of instances in the cluster
                    type: integer
                  parameter:
                    description: The parameter group
                    type: array
                    items:
                      type: object
                      properties:
                        applyMethod:
                          description: The apply method of the parameter
                          type: string
                        name:
                          description: The name of the parameter
                          type: string
                        value:
                          description: The value of the parameter
                          type: string
                  passwordSecret:
                    description: The secret reference to the password of the master user.
                    type: object
                    properties:
                      name:
                        description: The name of the secret.
                        type: string
                      key:
                        description: The key in the secret.
                        type: string
                      namespace:
                        description: The namespace of the secret.
                        type: string
                  port:
                    description: "Port at which db server listens"
                    type: integer
                    default: 5432
                  preferredBackupWindow:
                    description: The daily time range during which automated backups are created
                    type: string
                  preferredMaintenanceWindow:
                    description: The preferred maintenance window
                    type: string
                  region:
                    description: Region
                    type: string
                  restoreToPointInTime:
                    description: The point in time to restore to
                    type: string
                  skipFinalSnapshot:
                    description: Indicates that final snapshot should be skipped before destroy
                    type: boolean
                    default: false
                  snapshotIdentifier:
                    description: The snapshot identifier
                    type: string
                  storageEncrypted:
                    description: The type of storage
                    type: boolean
                    default: true
                  storageType:
                    description: The type of storage
                    type: string
                  subnets:
                    description: The comma seperated list of subnet-ids to create the subnetgroup
                    type: string
                  azs:
                    description: The comma separated list of availability zones to use
                    type: string
                  username:
                    description: The name of master user
                    type: string
                  vpcCidr:
                    description: Comma separated Vpc CIDR blocks
                    type: string
                  vpcId:
                    description: Vpc id
                    type: string
                required:
                  - applyImmediately
                  - backupRetentionPeriod
                  - databaseName
                  - dbClusterInstanceClass
                  - deletionProtection
                  - engine
                  - engineVersion
                  - family
                  - finalSnapshotIdentifier
                  - instanceCount
                  - passwordSecret
                  - port
                  - preferredBackupWindow
                  - preferredMaintenanceWindow
                  - region
                  - subnets
                  - azs
                  - username
                  - vpcCidr
                  - vpcId