apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xs3bucket.objectstore.mojaloop.io
spec:
  group: objectstore.mojaloop.io
  names:
    kind: XS3Bucket
    plural: xs3bucket
  claimNames:
    kind: S3Bucket
    plural: s3buckets
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              managementPolicies:
                default:
                  - "*"
                description: |-
                  A ManagementAction represents an action that the Crossplane controllers
                  can take on an external resource.
                items:
                  description: |-
                    A ManagementAction represents an action that the Crossplane controllers
                    can take on an external resource.
                  enum:
                    - Observe
                    - Create
                    - Update
                    - Delete
                    - LateInitialize
                    - "*"
                  type: string
                type: array
              parameters:
                type: object
                properties:
                  bucketName:
                    type: string
                  bucketRegion:
                    type: string
                    default: "eu-west-1"
                  providerConfigName:
                    type: string
                    default: "aws-cp-upbound-provider-config"
                  destinationNamespace:
                    type: string
                    default: crossplane-system
                  forceDestroy:
                    type: boolean
                    default: false
                  deletionPolicy:
                    type: string
                    default: "Delete"
          status:
            type: object
            properties:
              iamUserARN:
                type: string
              bucketARN:
                type: string
              iamUserId:
                type: string
              accessKeyID:
                type: string
              accessKeyIDEncoded:
                type: string
              secretAccessKey:
                type: string
              secretAccessKeyEncoded:
                type: string