apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xcidrs.cidr.mojaloop.io
spec:
  defaultCompositeDeletePolicy: Foreground
  group: cidr.mojaloop.io
  names:
    kind: XCIDR
    plural: xcidrs
  claimNames:
    kind: CIDR
    plural: cidrs
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  description: CIDR Input parameters
                  type: object
                  properties:
                    cidrFunc:
                      type: string
                      enum:
                        - cidrsubnet
                        - cidrsubnets
                        - cidrhost
                        - cidrnetmask
                        - cidrsubnetloop
                        - multiprefixloop
                    subnets:
                      type: array
                      items:
                        type: object
                        properties:
                          prefix:
                            type: string
                          newBits:
                            type: array
                            items:
                              type: integer
                    cidrBlock:
                      type: string
                    newBits:
                      type: array
                      items:
                        type: integer
                    azs:
                      type: array
                      items:
                        type: string
                    hostNum:
                      type: integer
                    offset:
                      type: integer
                    outputField:
                      type: string
              required:
                - parameters
            status:
              description: Representing observed state.
              properties:
                atFunction:
                  description: Function execution results.
                  type: object
                  properties:
                    cidr:
                      description: CIDR function results.
                      type: array
                      items:
                        type: string
                cidr:
                  description: CIDR observed status.
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
