---
apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: cidr
spec:
  dependsOn:
    ## Functions
    - provider: xpkg.upbound.io/upbound/function-cidr
      version: ">=v0.6.0"
  crossplane:
    version: ">=v1.14"
  skipDependencyResolution: true
