apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xvaultpostconfig.vault.mojaloop.io
spec:
  defaultCompositeDeletePolicy: Foreground
  group: vault.mojaloop.io
  names:
    kind: XVaultPostConfig
    plural: xvaultpostconfig
  claimNames:
    kind: VaultPostConfig
    plural: vaultpostconfig
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              managementPolicies:
                default:
                  - "*"
                description: |-
                  A ManagementAction represents an action that the Crossplane controllers
                  can take on an external resource.
                items:
                  description: |-
                    A ManagementAction represents an action that the Crossplane controllers
                    can take on an external resource.
                  enum:
                    - Observe
                    - Create
                    - Update
                    - Delete
                    - LateInitialize
                    - "*"
                  type: string
                type: array
              providerConfigsRef:
                type: object
                description: |-
                  The name of the provider config to use for the source and destination k8s providers.
                required:
                  - vaultProviderName
                properties:
                  vaultProviderName:
                    type: string
                    description: |-
                      The name of the provider config to use for the vault provider.
              parameters:
                type: object
                properties:
                  kvPath:
                    type: string
                    description: |-
                      The path for the KV secrets engine.
                    default: "secret"
                  k8sAdminAuthPath:
                    type: string
                    description: |-
                      The auth path for Kubernetes authentication.
                    default: "kubernetes/admin"
                  k8sAdminRoleName:
                    type: string
                    description: |-
                      The name of the Kubernetes admin role.
                    default: "vault-admin"
                  adminPolicyName:
                    type: string
                    description: |-
                      The name of the admin policy.
                    default: "vault-admin"
                  readKvSecretsPolicyName:
                    type: string
                    description: |-
                      The name of the read-only policy for KV secrets.
                    default: "read-all-kv-secrets"
