apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: objectstoreuser
  labels:
    crossplane.io/xrd: xobjectstoreuser.objectstore.mojaloop.io
spec:
  compositeTypeRef:
    apiVersion: objectstore.mojaloop.io/v1alpha1
    kind: XObjectStoreUser
  mode: Pipeline
  pipeline:
    - step: kcl-routing
      functionRef:
        name: function-kcl
      input:
        apiVersion: krm.kcl.dev/v1alpha1
        kind: KCLInput
        spec:
          source: |
            $KCL_FUNCTION_CODE
    - step: auto-ready
      functionRef:
        name: function-auto-ready
