apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: utils
spec:
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-family-aws
      version: ">=v1.21.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-docdb
      version: ">=v1.21.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-ec2
      version: ">=v1.21.0"
    ## Functions
    - provider: xpkg.upbound.io/crossplane-contrib/function-kcl
      version: ">=v0.9.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
      version: ">=v0.2.1"
  crossplane:
    version: ">=v1.14"
  skipDependencyResolution: true
