apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xoperatorpostconfig.nb.mojaloop.io
spec:
  defaultCompositeDeletePolicy: Foreground
  group: nb.mojaloop.io
  names:
    kind: XOperatorPostConfig
    plural: xoperatorpostconfig
  claimNames:
    kind: OperatorPostConfig
    plural: operatorpostconfig
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                managementPolicies:
                  default:
                    - "*"
                  description: |-
                    THIS IS A BETA FIELD. It is on by default but can be opted out
                    through a Crossplane feature flag.
                    ManagementPolicies specify the array of actions Crossplane is allowed to
                    take on the managed and external resources.
                    This field is planned to replace the DeletionPolicy field in a future
                    release. Currently, both could be set independently and non-default
                    values would be honored if the feature flag is enabled. If both are
                    custom, the DeletionPolicy field will be ignored.
                    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
                    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
                  items:
                    description: |-
                      A ManagementAction represents an action that the Crossplane controllers
                      can take on an external resource.
                    enum:
                      - Observe
                      - Create
                      - Update
                      - Delete
                      - LateInitialize
                      - "*"
                    type: string
                  type: array
                providerConfigsRef:
                  type: object
                  description: |-
                    The name of the provider config to use for the source and destination k8s providers.
                  required:
                    - netbirdProviderConfigName
                  properties:
                    netbirdProviderConfigName:
                      type: string
                      description: |-
                        The name of the provider config to use for the destination k8s provider.
                parameters:
                  type: object
                  properties:
                    networkResource:
                      type: object
                      properties:
                        name:
                          type: string
                          description: The name of network resource to create.
                        CIDR:
                          type: string
                          description: The cidr of network resource to create.
                        networkName:
                          type: string
                          description: The name of the network to attach resource to.
                    groupNames:
                      type: object
                      properties:
                        networkResourceGroup:
                          type: string
                          description: The name of the group to assign to the routing peers.
