apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xconfigmapfromsecret.utils.mojaloop.io
spec:
  defaultCompositeDeletePolicy: Foreground
  group: utils.mojaloop.io
  names:
    kind: XConfigMapfromSecret
    plural: xconfigmapfromsecret
  claimNames:
    kind: ConfigMapfromSecret
    plural: configmapfromsecret
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              managementPolicies:
                default:
                  - "*"
                description: |-
                  THIS IS A BETA FIELD. It is on by default but can be opted out
                  through a Crossplane feature flag.
                  ManagementPolicies specify the array of actions Crossplane is allowed to
                  take on the managed and external resources.
                  This field is planned to replace the DeletionPolicy field in a future
                  release. Currently, both could be set independently and non-default
                  values would be honored if the feature flag is enabled. If both are
                  custom, the DeletionPolicy field will be ignored.
                  See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
                  and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
                items:
                  description: |-
                    A ManagementAction represents an action that the Crossplane controllers
                    can take on an external resource.
                  enum:
                    - Observe
                    - Create
                    - Update
                    - Delete
                    - LateInitialize
                    - "*"
                  type: string
                type: array
              providerConfigsRef:
                type: object
                description: |-
                  The name of the provider config to use for the source and destination k8s providers.
                required:
                  - k8sProviderName
                properties:
                  k8sProviderName:
                    type: string
                    description: |-
                      The name of the provider config to use for the k8s provider.
              parameters:
                type: object
                properties:
                  keyMappings:
                    type: array
                    items:
                      type: object
                      required: ["sourceKey", "destinationKey"]
                      properties:
                        sourceKey:
                          type: string
                          description: |-
                            The key in the source secret to use.
                        destinationKey:
                          type: string
                          description: |-
                            The key in the destination configmap to use.
                  sourceSecret:
                    type: object
                    description: |-
                      The source secret with properties to use
                    required:
                      - namespace
                      - name
                    properties:
                      namespace:
                        type: string
                        description: |-
                          Namespace of the secret to use.
                      name:
                        type: string
                        description: |-
                          Name of the secret to use.
                  destinationConfigMap:
                    type: object
                    description: |-
                      The destination configmap parameters
                    required:
                      - namespace
                      - name
                    properties:
                      namespace:
                        type: string
                        description: |-
                          Namespace of the configmap to create.
                      name:
                        type: string
                        description: |-
                          Name of the configmap to be created.