apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpgcluster.sc.mojaloop.io
spec:
  defaultCompositeDeletePolicy: Foreground
  group: sc.mojaloop.io
  names:
    kind: XPGCluster
    plural: xpgcluster
  claimNames:
    kind: PGCluster
    plural: pgcluster
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              managementPolicies:
                default:
                  - "*"
                description: |-
                  A ManagementAction represents an action that the Crossplane controllers
                  can take on an external resource.
                items:
                  description: |-
                    A ManagementAction represents an action that the Crossplane controllers
                    can take on an external resource.
                  enum:
                    - Observe
                    - Create
                    - Update
                    - Delete
                    - LateInitialize
                    - "*"
                  type: string
                type: array
              providerConfigsRef:
                type: object
                description: |-
                  The name of the provider config to use for the remote and local k8s providers.
                required:
                  - scK8sProviderName
                  - ccK8sProviderName
                properties:
                  ccK8sProviderName:
                    type: string
                    description: |-
                      The name of the provider config to use for the local k8s provider.
                  scK8sProviderName:
                    type: string
                    description: |-
                      The name of the provider config to use for the remote k8s provider.
              parameters:
                type: object
                properties:
                  clusterName:
                    type: string
                    description: Name for the consumer cluster
                  externalServiceName:
                    type: string
                    description: Name for the external service object created
                  appNamespace:
                    type: string
                    description: Namespace for the consumer application
                  crVersion:
                    type: string
                    description: Type of object to be synced
                    default: "2.5.0"
                  pgVersion:
                    type: number
                    description: Type of object to be synced
                    default: 16
                  dbSecret:
                    type: string
                    description: Secret name to store the DB password
                  dbUsername:
                    type: string
                    description: Name of the database user to be created
                  dbName:
                    type: string
                    description: Name of the database to be created
                  replicas:
                    type: number
                    description: Number of replicas for the DB instance
                    default: 1
                  storageSize:
                    type: string
                    description: Storage size for the DB PVC
                    default: 10Gi
                  image:
                    type: string
                    description: Percona PostgreSQL image to use for the cluster
                  resources:
                    type: object
                    description: CPU/Memory resource requests and limits
                    properties:
                      limits:
                        type: object
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                      requests:
                        type: object
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                  priorityClassName:
                    type: string
                    description: Priority class for scheduling pods
                  tolerations:
                    type: array
                    description: Tolerations applied to DB and proxy pods
                    items:
                      type: object
                      properties:
                        key:
                          type: string
                        operator:
                          type: string
                        value:
                          type: string
                        effect:
                          type: string
                  backup:
                    type: object
                    description: Backup configuration
                    properties:
                      image:
                        type: string
                        description: Image used for pgbackrest
                      objectStoreEndpoint:
                        type: string
                      bucket:
                        type: string
                      bucketRegion:
                        type: string
                      fullBackupCronSchedule:
                        type: string
                      differentialBackupCronSchedule:
                        type: string
                  proxy:
                    type: object
                    description: Proxy configuration for PgBouncer
                    properties:
                      pgBouncer:
                        type: object
                        properties:
                          image:
                            type: string
                          replicas:
                            type: number
                          exposeSuperusers:
                            type: boolean
                          globalConfig:
                            type: object
                            properties:
                              pool_mode:
                                type: string
                              query_wait_timeout:
                                type: string
                              max_prepared_statements:
                                type: string
                          resources:
                            type: object
                            properties:
                              limits:
                                type: object
                                properties:
                                  cpu:
                                    type: string
                                  memory:
                                    type: string
                              request:
                                type: object
                                properties:
                                  cpu:
                                    type: string
                                  memory:
                                    type: string
                          expose:
                            type: object
                            properties:
                              type:
                                type: string
                              loadBalancerSourceRanges:
                                type: array
                                items:
                                  type: string
                              annotations:
                                type: object
                                additionalProperties:
                                  type: string
                              labels:
                                type: object
                                additionalProperties:
                                  type: string
                          tolerations:
                            type: array
                            items:
                              type: object
                              properties:
                                key:
                                  type: string
                                operator:
                                  type: string
                                value:
                                  type: string
                                effect:
                                  type: string
