apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: awsroute53record
  labels:
    crossplane.io/xrd: xawsroute53record.utils.aws.mojaloop.io
spec:
  compositeTypeRef:
    apiVersion: utils.aws.mojaloop.io/v1alpha1
    kind: XAWSRoute53Record
  mode: Pipeline
  pipeline:

    - step: kcl
      functionRef:
        name: function-kcl
      input:
        apiVersion: krm.kcl.dev/v1alpha1
        kind: KCLInput
        spec:
          source: |
            $KCL_FUNCTION_CODE

    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready
