apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xvaultoidc.vault.mojaloop.io
spec:
  defaultCompositeDeletePolicy: Foreground
  group: vault.mojaloop.io
  names:
    kind: XVaultOIDC
    plural: xvaultoidc
  claimNames:
    kind: VaultOIDC
    plural: vaultoidc
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              managementPolicies:
                default:
                  - "*"
                description: |-
                  A ManagementAction represents an action that the Crossplane controllers
                  can take on an external resource.
                items:
                  description: |-
                    A ManagementAction represents an action that the Crossplane controllers
                    can take on an external resource.
                  enum:
                    - Observe
                    - Create
                    - Update
                    - Delete
                    - LateInitialize
                    - "*"
                  type: string
                type: array
              providerConfigsRef:
                type: object
                description: |-
                  The name of the provider config to use for the source and destination k8s providers.
                required:
                  - zitadelProviderName
                  - kubernetesProviderName
                properties:
                  zitadelProviderName:
                    type: string
                    description: |-
                      The name of the provider config to use for the zitadel provider.
                  kubernetesProviderName:
                    type: string
                    description: |-
                      The name of the provider config to use for the kubernetes provider.
                  vaultProviderName:
                    type: string
                    description: |-
                      The name of the provider config to use for the vault provider.
              parameters:
                type: object
                required:
                  - vaultFqdn
                  - zitadelFqdn
                  - vaultNamespace
                  - zitadelAdminHumanUserIdRef
                properties:
                  vaultFqdn:
                    type: string
                    description: |-
                      FQDN for Vault
                  zitadelFqdn:
                    type: string
                    description: |-
                      FQDN for Zitadel
                  adminRbacGroup:
                    type: string
                    description: |-
                      RBAC group in IDM for admin access via OIDC
                    default: "vault_administrators"
                  userRbacGroup:
                    type: string
                    description: |-
                      RBAC group in IDM for user access via OIDC
                    default: "vault_users"
                  vaultNamespace:
                    type: string
                    description: |-
                      Namespace where Vault is installed
                  oidcProviderGroupClaimPrefix:
                    type: string
                    description: |-
                      OIDC Provider Group Claim Prefix
                  zitadelAdminHumanUserIdRef:
                    type: object
                    description: |-
                      Admin Zitadel human user ID
                    required:
                      - name
                      - namespace
                    properties:
                      name:
                        type: string
                        description: |-
                          Name of the secret to observe
                      namespace:
                        type: string
                        description: |-
                          Namespace of the secret to observe
                      key:
                        type: string
                        description: |-
                          Key of the secret to observe
                        default: "zitadel_admin_human_user_id"
                  organizationIdSecretRef:
                    type: object
                    description: |-
                      Organization ID secret
                    default:
                      name: "zitadel-post-config-init-output"
                      namespace: "zitadel"
                      key: "zitadel_org_id"
                    properties:
                      name:
                        type: string
                        description: |-
                          Name of the secret to observe
                        default: "zitadel-post-config-init-output"
                      namespace:
                        type: string
                        description: |-
                          Namespace of the secret to observe
                        default: "zitadel"
                      key:
                        type: string
                        description: |-
                          Key of the secret to observe
                        default: "zitadel_org_id"
