apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpostconfig.netbird.infitx.org
spec:
  defaultCompositeDeletePolicy: Foreground
  group: netbird.infitx.org
  names:
    kind: XPostConfig
    plural: xpostconfig
  claimNames:
    kind: PostConfig
    plural: postconfig
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              managementPolicies:
                default:
                  - "*"
                description: |-
                  THIS IS A BETA FIELD. It is on by default but can be opted out
                  through a Crossplane feature flag.
                  ManagementPolicies specify the array of actions Crossplane is allowed to
                  take on the managed and external resources.
                  This field is planned to replace the DeletionPolicy field in a future
                  release. Currently, both could be set independently and non-default
                  values would be honored if the feature flag is enabled. If both are
                  custom, the DeletionPolicy field will be ignored.
                  See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
                  and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
                items:
                  description: |-
                    A ManagementAction represents an action that the Crossplane controllers
                    can take on an external resource.
                  enum:
                    - Observe
                    - Create
                    - Update
                    - Delete
                    - LateInitialize
                    - "*"
                  type: string
                type: array
              providerConfigsRef:
                type: object
                description: |-
                  The name of the provider config to use for the source and destination k8s providers.
                required:
                  - netbirdProviderConfigName
                  - k8sProviderConfigName
                properties:
                  k8sProviderConfigName:
                    type: string
                    description: |-
                      The name of the provider config to use for the source k8s provider.
                  netbirdProviderConfigName:
                    type: string
                    description: |-
                      The name of the provider config to use for the destination k8s provider.
              parameters:
                type: object
                properties:
                  ccClusterName:
                    type: string
                    description: The name of the CC cluster to use for the post-config.
                  environments:
                    type: array
                    items:
                      type: string
                    description: The environments to use for the post-config.
                  setupKey:
                    type: object
                    properties:
                      name:
                        type: string
                        description: The name of the setup key to use for the post-config.
                      namespace:
                        type: string
                        description: The namespace of the setup key to use for the post-config.
                      gwSetupKeySecretKey:
                        type: string
                        description: The key of the gateway setup key to use for the post-config.
                      buildSetupKeySecretKey:
                        type: string
                        description: The key of the build setup key to use for the post-config.
                  zitadelProjectId:
                    type: number
                    description: The ID of the Zitadel project to use for the post-config.
                  accountId:
                    type: string
                    description: The ID of the Netbird account to use for the post-config.
                  groupNames:
                    type: object
                    properties:
                      admin:
                        type: string
                        description: The name of the admin group to use for the post-config.
                      externalAccess:
                        type: string
                        description: The name of the external access group to use for the post-config.
