apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: nboperatorinstall
  labels:
    crossplane.io/xrd: xnboperatorinstall.netbird.infitx.org
spec:
  compositeTypeRef:
    apiVersion: netbird.infitx.org/v1alpha1
    kind: XNbOperatorInstall
  mode: Pipeline
  pipeline:
    - step: kcl
      functionRef:
        name: function-kcl
      input:
        apiVersion: krm.kcl.dev/v1alpha1
        kind: KCLInput
        spec:
          source: |
            $KCL_FUNCTION_CODE

    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready
