apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xnetbirdenvconfig.nb.mojaloop.io
spec:
  defaultCompositeDeletePolicy: Foreground
  group: nb.mojaloop.io
  names:
    kind: XNetbirdEnvConfig
    plural: xnetbirdenvconfig
  claimNames:
    kind: NetbirdEnvConfig
    plural: netbirdenvconfig
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                managementPolicies:
                  default:
                    - "*"
                  description: |-
                    THIS IS A BETA FIELD. It is on by default but can be opted out
                    through a Crossplane feature flag.
                    ManagementPolicies specify the array of actions Crossplane is allowed to
                    take on the managed and external resources.
                    This field is planned to replace the DeletionPolicy field in a future
                    release. Currently, both could be set independently and non-default
                    values would be honored if the feature flag is enabled. If both are
                    custom, the DeletionPolicy field will be ignored.
                    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
                    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
                  items:
                    description: |-
                      A ManagementAction represents an action that the Crossplane controllers
                      can take on an external resource.
                    enum:
                      - Observe
                      - Create
                      - Update
                      - Delete
                      - LateInitialize
                      - "*"
                    type: string
                  type: array
                providerConfigsRef:
                  type: object
                  description: |-
                    The name of the provider config to use for the source and destination k8s providers.
                  required:
                    - netbirdProviderConfigName
                    - k8sProviderConfigName
                  properties:
                    k8sProviderConfigName:
                      type: string
                      description: |-
                        The name of the provider config to use for the source k8s provider.
                    netbirdProviderConfigName:
                      type: string
                      description: |-
                        The name of the provider config to use for the destination k8s provider.
                parameters:
                  type: object
                  properties:
                    pushSecret:
                      type: object
                      description: Properties for pushing secrets to vault
                      properties:
                        esoPushSecret:
                          type: boolean
                          description: |-
                            Whether to push the secret to vault.
                          default: false
                        esoUpdatePolicy:
                          type: string
                          description: |-
                            Policy to update the secret on vault.
                          default: "Replace"
                        esoDeletePolicy:
                          type: string
                          description: |-
                            Policy to delete the secret on vault.
                          default: "Delete"
                        esoRefreshInterval:
                          type: string
                          description: |-
                            Interval to refresh the secret on vault.
                          default: "1m"
                        vaultSecretStore:
                          type: string
                          description: |-
                            Name of the secretstore on cluster for vault.
                          default: "vault-secret-store"
                        vaultSecretStoreKind:
                          type: string
                          description: |-
                            Kind of the secret store in vault.
                          default: "ClusterSecretStore"
                    envProperties:
                      type: object
                      description: The properties for a downstream network to connect to cc/sc.
                      properties:
                        setupKey:
                          type: object
                          properties:
                            name:
                              type: string
                              description: The name of the setup key to use for the config.
                            namespace:
                              type: string
                              description: The namespace of the setup key to use for the config.
                            vaultSecretPath:
                              type: string
                              description: |-
                                Path of the secret in vault.
                        groupNames:
                          type: object
                          properties:
                            ccNetworkResource:
                              type: string
                              description: The name of the external access group to use for the post-config.
                            envK8sNodes:
                              type: string
                              description: The name of the group for the env k8s nodes.
                        policy:
                          type: object
                          description: |-
                            The policy to use for the env k8s nodes.
                            This is used to create a policy that allows the env k8s nodes to connect to the cc/sc network resources.
                          properties:
                            ccPorts:
                              type: string
                              description: The ports to sc to allow in the policy.
