apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xsqlpercona.database.mojaloop.io
spec:
  defaultCompositeDeletePolicy: Foreground
  group: database.mojaloop.io
  names:
    kind: XSqlPercona
    plural: xsqlpercona
  claimNames:
    kind: SqlPercona
    plural: sqlpercona
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              managementPolicies:
                default:
                  - "*"
                description: |-
                  A ManagementAction represents an action that the Crossplane controllers
                  can take on an external resource.
                items:
                  description: |-
                    A ManagementAction represents an action that the Crossplane controllers
                    can take on an external resource.
                  enum:
                    - Observe
                    - Create
                    - Update
                    - Delete
                    - LateInitialize
                    - "*"
                  type: string
                type: array
              providerConfigsRef:
                type: object
                description: |-
                  The name of the provider config to use for the remote and local k8s providers.
                required:
                  - scK8sProviderName
                  - ccK8sProviderName
                properties:
                  ccK8sProviderName:
                    type: string
                    description: |-
                      The name of the provider config to use for the local k8s provider.
                  scK8sProviderName:
                    type: string
                    description: |-
                      The name of the provider config to use for the remote k8s provider.
              parameters:
                type: object
                properties:
                  consumeClusterType:
                    type: string
                    description: Type of consumer cluster
                    enum:
                      - controlcenter
                      - environment
                  clusterName:
                    type: string
                    description: Name for the consumer cluster
                  externalServiceName:
                    type: string
                    description: Name for the external service object created
                  postgres:
                    type: object
                    properties:
                      crVersion:
                        type: string
                        description: Type of object to be synced
                        default: "2.5.0"
                      pgVersion:
                        type: number
                        description: Type of object to be synced
                        default: 16
                      dbSecret:
                        type: string
                        description: Type of object to be synced
                        default: db-secret
                      replicas:
                        type: number
                        description: Type of object to be synced
                        default: 1
                      storageSize:
                        type: string
                        description: Type of object to be synced
                        default: 10Gi
