name: 🚀 Crossplane Package Pipeline

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      registry:
        required: true
        type: string
      packages_dir:
        required: true
        type: string
      release_name:
        required: false
        type: string
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true

jobs:
  calculate-version:
    name: 🔢 Calculate Version
    runs-on: ubuntu-latest
    outputs:
      next_version: ${{ steps.version.outputs.next_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 🔢 Calculate Version
        id: version
        run: |
          bash .github/scripts/get-next-version.sh ${{ inputs.package }} > base_version.txt
          BASE_VERSION=$(cat base_version.txt)
          if [[ "${{ github.ref_type }}" != "tag" && "${{ github.ref }}" != "refs/heads/main" ]]; then
            SUFFIX="-pr${{ github.event.pull_request.number }}-${{ github.run_id }}"
            echo "next_version=${BASE_VERSION}${SUFFIX}" >> $GITHUB_OUTPUT
          else
            echo "next_version=${BASE_VERSION}" >> $GITHUB_OUTPUT
          fi

  pull-request-package:
    uses: mojaloop/iac-crossplane-packages/.github/workflows/xplane_pull_request.yaml@feat/CTO-1001_align_packages
    name: 🧪 PR Preview Package
    needs: [calculate-version]
    if: ${{ github.ref_type != 'tag' && github.ref != 'refs/heads/main' }}
    secrets: inherit
    with:
      CROSSPLANE_PACKAGES_DIR: ${{ inputs.packages_dir }}
      CROSSPLANE_REGISTRY_URL: ${{ inputs.registry }}
      SUBPATH: ${{ inputs.package }}
      NEXT_VERSION: v${{ needs.calculate-version.outputs.next_version }}

  release-package:
    uses: mojaloop/iac-crossplane-packages/.github/workflows/xplane_pull_request.yaml@feat/CTO-1001_align_packages
    name: 🚀 Release Package
    needs: [calculate-version]
    if: ${{ github.ref_type == 'tag' }}
    secrets: inherit
    with:
      CROSSPLANE_PACKAGES_DIR: ${{ inputs.packages_dir }}
      CROSSPLANE_REGISTRY_URL: ${{ inputs.registry }}
      SUBPATH: ${{ inputs.package }}
      NEXT_VERSION: v${{ needs.calculate-version.outputs.next_version }}
